version: '3.3'

services:

  pgsql:
    build:
      context: pgsql
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_DB: "novels"
      POSTGRES_PASSWORD: "112233qq"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/posgresql/data

    networks:
      - default

    ports:
      - "5432:5432"

    restart: always

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    
    restart: always

    volumes:
      - ./nginx/content:/home

    ports:
      - "80:80"

    networks:
      - default

  django:
    build:
      context: django-container
      dockerfile: Dockerfile
    container_name: django

    environment:
      POSTGRES_USER: "admin"
      POSTGRES_DB: "novels"
      POSTGRES_PASSWORD: "112233qq"
      POSTGRES_HOST_AUTH_METHOD: trust
   
    restart: always

    ports:
      - "8080:8080"

    networks:
      - default

    depends_on:
      - pgsql
    
    command: sh -c "python3 /home/vagrant/django-container/novels_project/manage.py migrate &&
                    python3 /home/vagrant/django-container/novels_project/manage.py runserver 0.0.0.0:8080"

volumes:
  pgdata:

networks:
  default:
    driver: "bridge"
    external: false