login = "hstiv"

server_name = "#{login}S"
server_ip   = "192.168.42.110"

Vagrant.configure("2") do |config|

  config.vm.box     = "ubuntu/focal64"
  config.vm.box_url = "C:\\Users\\monster-lt\\Downloads\\focal-server-cloudimg-amd64-vagrant.box"
#   config.vm.box_url = "https://app.vagrantup.com/ubuntu/boxes/focal64/versions/20220520.0.0/providers/virtualbox.box"

  config.vm.synced_folder ".", "/home/vagrant"

  config.vm.provider :virtualbox do |v, override|
    v.customize ["modifyvm", :id, "--memory", 2024]
    v.customize ["modifyvm", :id, "--cpus", 1]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  # Server
  config.vm.define server_name do |control|
    control.vm.hostname = server_name
    control.vm.network "private_network", ip: server_ip
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", server_name]
    end
    control.vm.provision "shell", privileged: true, inline:<<-SHELL
    sudo snap install docker
    sudo apt install make
    make up
    SHELL
  end

end