# Generated by Django 4.0.4 on 2022-05-03 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='location',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='location',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='novel_id',
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='country',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Genreext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.genre')),
                ('novel_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.novel')),
            ],
        ),
    ]
