# Generated by Django 4.0.4 on 2022-05-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('country', models.CharField(blank=True, max_length=64, null=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ('name', 'bio', 'country'),
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Название новеллы', max_length=128, null=True, verbose_name='Название')),
                ('original_title', models.CharField(blank=True, help_text='Оригинальное название новеллы', max_length=128, null=True, verbose_name='Оригинальное название')),
                ('description', models.TextField(blank=True, help_text='Описание', null=True, verbose_name='Описание')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новелла',
                'verbose_name_plural': 'Новеллы',
                'ordering': ('title', 'description', 'author', 'original_title'),
            },
        ),
    ]
